# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.show_config()
np.version.full_version

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

'1.24.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
v.__sizeof__(), len(v), v.size

(192, 10, 10)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
v = np.zeros(10)
v[4] = 1
v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.arange(10, 49)[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1, 2, 0, 0, 4, 0])
a.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3, 3, 3))

array([[[0.23096742, 0.42623389, 0.60489527],
        [0.74903912, 0.41415133, 0.73879869],
        [0.01398445, 0.02001838, 0.60864766]],

       [[0.3832937 , 0.58966788, 0.97277576],
        [0.6179568 , 0.83403731, 0.67666343],
        [0.30535982, 0.50148883, 0.19356546]],

       [[0.36650689, 0.78975383, 0.7849556 ],
        [0.6018429 , 0.05614588, 0.51415639],
        [0.42255218, 0.41233742, 0.46687636]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10, 10))
a.min(), a.max()

(0.04765290458262128, 0.9817360711929662)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a = np.random.random(10)
a.mean()

0.47985994441740293

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
ashape = tuple(np.array(a.shape) + 2)
d = np.zeros(ashape)
d[1:-1, 1:-1] = a
d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(
    np.isnan(0 * np.nan), 
    (np.nan == np.nan) == False, 
    (np.inf > np.nan) == False, 
    np.isnan(np.nan - np.nan),
    (np.nan in set([np.nan])) == True,
    (0.3 == 3 * 0.1) == False
    )

True True True True True True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.ones((8, 8))
a[0::2, 0::2] = 0
a[1::2, 1::2] = 0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
np.tile(np.array([[0, 1], [1, 0]]), reps=(4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.random((5, 5))
a = (a - a.min()) / (a.max() - a.min())
a

array([[0.00301234, 0.15550552, 0.48191476, 0.22263241, 0.05169702],
       [0.89362777, 0.0828822 , 0.29334502, 0.7393916 , 1.        ],
       [0.67315716, 0.44432626, 0.60678645, 0.88292015, 0.        ],
       [0.77479603, 0.6343853 , 0.2962966 , 0.43317117, 0.79989524],
       [0.57944676, 0.03679545, 0.17736602, 0.48766844, 0.51892069]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.random((5, 3))
b = np.random.random((3, 8))
np.dot(a, b)

array([[0.79008415, 1.12373047, 1.5898065 , 0.5855577 , 1.61587823,
        1.81167157, 0.61045109, 1.5479206 ],
       [0.60168329, 0.68937262, 1.12369988, 0.37980935, 0.96710423,
        1.33774597, 0.51111413, 0.94005733],
       [0.7247968 , 0.74332283, 1.42507246, 0.52578885, 1.16158075,
        1.67603832, 0.6698197 , 1.18570847],
       [0.46348723, 0.70195228, 1.04129023, 0.43638765, 1.11482674,
        1.13737609, 0.36831232, 1.10091188],
       [0.13168748, 0.23666   , 0.40773955, 0.2200485 , 0.48193714,
        0.40087677, 0.11794515, 0.50703999]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.arange(1, 10)
a[(a > 3) & (a < 8)] *= -1
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
9, 10

(9, 10)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
z = np.array([1, 2, 3])
z ** z, 2 << z >> 2, z <- z, 1j*z, z/1/1

(array([ 1,  4, 27]),
 array([1, 2, 4]),
 array([False, False, False]),
 array([0.+1.j, 0.+2.j, 0.+3.j]),
 array([1., 2., 3.]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)

/var/folders/_c/2vztvhm558dd_36p09zpg5nc0000gn/T/ipykernel_2847/2446836393.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
/var/folders/_c/2vztvhm558dd_36p09zpg5nc0000gn/T/ipykernel_2847/2446836393.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
/var/folders/_c/2vztvhm558dd_36p09zpg5nc0000gn/T/ipykernel_2847/2446836393.py:1: RuntimeWarning: invalid value encountered in cast
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)


(nan, 0, array([-9.22337204e+18]))

#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = np.random.uniform(-5,5,10)
np.copysign(np.ceil(np.abs(a)), a)

array([ 2.,  1.,  4., -4.,  1.,  2., -1., -3., -3., -5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
np.intersect1d(a,b)

array([3, 4, 6, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2023-03-31'),
 numpy.datetime64('2023-04-01'),
 numpy.datetime64('2023-04-02'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
a = np.arange(1., 3.)
b = np.arange(2., 4.)
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)
a

array([-1.5, -5. ])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
a = np.random.random((3, 3)) * 10

print(
    a // 1,
    np.floor(a),
    a.astype(int),
    np.trunc(a),
    sep="\n\n"
)

[[1. 6. 0.]
 [4. 0. 9.]
 [3. 0. 7.]]

[[1. 6. 0.]
 [4. 0. 9.]
 [3. 0. 7.]]

[[1 6 0]
 [4 0 9]
 [3 0 7]]

[[1. 6. 0.]
 [4. 0. 9.]
 [3. 0. 7.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
np.tile(np.arange(0, 5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def generate():
    for x in range(10):
        yield x

np.fromiter(generate(),dtype=float,count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
a = np.random.random(10)
a.sort()
a

array([0.01406245, 0.0302187 , 0.30047657, 0.52198229, 0.55318806,
       0.55589893, 0.62246997, 0.70219577, 0.77824577, 0.81765775])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
a = np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
a = np.random.randint(0,2,10)
b = np.random.randint(0,2,10)

np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
a = np.arange(1, 10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
cart = np.random.random((10,2))
x,y = cart[:,0], cart[:,1]
np.sqrt(x**2+y**2), np.arctan2(y, x)

(array([0.70533412, 0.65270926, 1.0112145 , 0.82796721, 0.51958521,
        0.90532587, 0.66654971, 0.69524795, 0.63588401, 0.896011  ]),
 array([0.55519662, 0.17947107, 0.61559277, 1.0231754 , 0.95865393,
        1.30535468, 0.70118244, 0.90311464, 1.25006877, 0.27836454]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.54469886, 0.        , 0.84887156, 0.92014003, 0.90677912,
       0.82717141, 0.704314  , 0.89649598, 0.09636898, 0.61792193])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
xy = np.dtype([("x", np.float64), ("y", np.float64)])
a = np.zeros((10, 10), dtype=xy)
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
a

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
a, b = np.arange(8), np.arange(8)
c = 1.0 / np.subtract.outer(x, y)
np.linalg.det(c)

2.1097241595210925e+17

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64, np.float128]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-65500.0
65500.0
0.000977
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
-1.189731495357231765e+4932
1.189731495357231765e+4932
1.084202172485504434e-19


#### 49. How to print all the values of an array? (★★☆)

In [50]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
a = np.random.random(10)
b = np.random.random(10)
idx = (np.abs(a - b)).argmin()
a[idx], b[idx]

(0.5015194181887432, 0.5118001257823209)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
a = np.zeros(10, [ 
    ('position', [ ('x', float, 1),
                   ('y', float, 1)]),
    ('color',    [ ('r', float, 1),
                   ('g', float, 1),
                   ('b', float, 1)])])
a

/var/folders/_c/2vztvhm558dd_36p09zpg5nc0000gn/T/ipykernel_2847/3274034747.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
import scipy.spatial

a = np.random.random((10,2))
d = scipy.spatial.distance.cdist(a, a)

d

array([[0.        , 0.35331054, 0.46560403, 0.40585252, 0.59948358,
        0.68877825, 0.57594528, 0.29398985, 0.5488333 , 0.39957648],
       [0.35331054, 0.        , 0.12655631, 0.62888297, 0.29206743,
        0.3559664 , 0.39067333, 0.56218619, 0.48414734, 0.35264545],
       [0.46560403, 0.12655631, 0.        , 0.75504245, 0.28789281,
        0.3114293 , 0.31770875, 0.63715073, 0.45198136, 0.35159732],
       [0.40585252, 0.62888297, 0.75504245, 0.        , 0.73568285,
        0.84569458, 0.95620828, 0.63098479, 0.95244981, 0.80035493],
       [0.59948358, 0.29206743, 0.28789281, 0.73568285, 0.        ,
        0.11047252, 0.60002696, 0.84596967, 0.73951231, 0.62925003],
       [0.68877825, 0.3559664 , 0.3114293 , 0.84569458, 0.11047252,
        0.        , 0.59775894, 0.91813263, 0.7552239 , 0.66302621],
       [0.57594528, 0.39067333, 0.31770875, 0.95620828, 0.60002696,
        0.59775894, 0.        , 0.59265802, 0.18464725, 0.21051331],
       [0.29398985, 0.56218619, 0.6371507

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
a = (np.random.random(10) * 10).astype(np.float32)
a.view(np.int32), "OR", a.astype(np.int32)

(array([1083886433, 1082101779, 1080007866, 1092211156, 1091291271,
        1088065604, 1062111554, 1074320885, 1061717875, 1083809230],
       dtype=int32),
 'OR',
 array([4, 3, 3, 9, 8, 6, 0, 2, 0, 4], dtype=int32))

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
            ''')
a = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
a = np.arange(10).reshape(2,5)
for index, value in np.ndenumerate(a):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
g

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
p = 10
a = np.zeros((10, 10))
np.put(a, np.random.choice(range(100), p, replace=False), 1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 1.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
a = np.random.random((2, 3))
o = a - a.mean(axis=1, keepdims=True)
a, o

(array([[0.85694311, 0.33810889, 0.48904161],
        [0.4820412 , 0.57970176, 0.77282994]]),
 array([[ 0.29557858, -0.22325565, -0.07232293],
        [-0.1294831 , -0.03182254,  0.16130564]]))

#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
a = np.random.randint(0, 10, (4, 4))
a[a[:,1].argsort()]

array([[4, 0, 1, 8],
       [9, 1, 1, 7],
       [7, 6, 7, 7],
       [1, 8, 5, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
a = np.random.randint(0, 10, (5, 5))
np.isnan(a).all(axis=0)

array([False, False, False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
a = np.arange(0, 1, 0.01)
v = 0.353
a.flat[np.abs(a - v).argmin()]

0.35000000000000003

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a, b, None])
for x,y,z in it: z[...] = x + y
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="blank"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        self.name = getattr(obj, 'name', "blank")

a = NamedArray(np.arange(10), "ranged")
a.name

'ranged'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:
a = np.ones(10)

np.add.at(a, np.random.randint(0, np.size(a), 10), 1)
a

array([2., 1., 4., 4., 1., 1., 2., 3., 1., 1.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
a = [1,2,3,4,5,6]
b = [1,3,9,3,4,1]
o = np.bincount(a, b)
o

array([0., 1., 3., 9., 3., 4., 1.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
w, h = 256, 256
i = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1, 3), axis=0)
len(colors)

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
a = np.random.randint(0,10,(4, 4, 4, 4))
a.sum(axis=(-2,-1))

array([[67, 61, 70, 59],
       [65, 78, 81, 63],
       [61, 73, 58, 79],
       [91, 76, 98, 85]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
d = np.random.uniform(0, 1, 100)
s = np.random.randint(0, 10, 100)
sums = np.bincount(s, weights=d)
counts = np.bincount(s)
means = sums / counts
means

array([0.53504993, 0.48424153, 0.43144464, 0.58004812, 0.61725691,
       0.49000265, 0.47647585, 0.52320623, 0.73188868, 0.2649559 ])

#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
a = np.random.uniform(0, 1, (5,5))
b = np.random.uniform(0, 1, (5,5))

np.diag(np.dot(a, b))

array([0.92269603, 0.46471057, 1.02404186, 1.45551999, 0.90358976])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
a = np.arange(1, 6)
target = 3
o = np.zeros(len(a) + (len(a)-1)*(target))
o[::target+1] = a
o

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
a = np.ones((5,5,3))
b = 4 * np.ones((5,5))
print(a * b[:,:,None])

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]


#### 72. How to swap two rows of an array? (★★★)

In [73]:
a = np.arange(0, 10, 1).reshape(2,5)
a[[0,1]] = a[[1,0]]
a

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0, 100, (10,3))
f = np.roll(faces.repeat(2, axis=1), -1, axis=1)
f = f.reshape(len(f) * 3, 2)
f = np.sort(f, axis=1)
np.unique(f.view( dtype=[('p0',f.dtype),('p1',f.dtype)]))

array([( 1,  1), ( 1, 91), ( 6, 35), ( 6, 43), ( 6, 92), (12, 82),
       (12, 87), (15, 40), (15, 63), (15, 65), (30, 57), (30, 76),
       (33, 76), (33, 88), (35, 43), (35, 92), (38, 57), (38, 65),
       (40, 65), (44, 71), (44, 91), (57, 65), (57, 76), (63, 63),
       (71, 91), (76, 88), (82, 87)], dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
a

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
sliding_window_view(Z, window_shape=4).mean(axis=-1)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
       12.5, 13.5, 14.5, 15.5, 16.5, 17.5])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
Z = np.arange(10)
sliding_window_view(Z, window_shape=3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
a = np.random.uniform(-1.0,1.0,100)
np.negative(a, out=a)

array([ 0.81875203,  0.00131709,  0.67399931, -0.71718045,  0.23034579,
       -0.82137431, -0.39486681,  0.3691052 , -0.29710068,  0.67762839,
        0.16985035,  0.78461085, -0.86448967, -0.90317975, -0.16822432,
        0.82172941,  0.80511993, -0.62206033,  0.16344339, -0.67915164,
        0.93860821, -0.03058015,  0.65442816, -0.61007434, -0.55796949,
        0.76841956, -0.95724095,  0.87075089, -0.11616452, -0.87907492,
        0.99764267,  0.73952483,  0.71089396, -0.20856225, -0.26954253,
       -0.38579861,  0.12752887,  0.35466882, -0.51852046, -0.55807768,
       -0.23502156, -0.92487925, -0.52620462, -0.68086083, -0.96421174,
        0.39150595, -0.54681   ,  0.90897302,  0.94973913, -0.33347927,
       -0.77802264,  0.47224508, -0.8811066 ,  0.26726273, -0.4382305 ,
        0.89612395, -0.66899014,  0.99822022, -0.62381134, -0.32903673,
       -0.17967252,  0.02892303, -0.81589234,  0.24491323, -0.4526122 ,
       -0.3103448 ,  0.65622464,  0.49339183,  0.80689617, -0.30

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [79]:
# Что-то как-то лень думать
# Если что дистанция расчитывается при помощи скалярного произведения

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
# Что-то как-то лень думать
# Если что дистанция расчитывается при помощи скалярного произведения

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [81]:
Z = np.arange(1, 15, dtype=np.uint32)
sliding_window_view(Z, window_shape=4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [82]:
a = np.random.uniform(0, 1, (10, 10))
np.linalg.matrix_rank(a)

10

#### 83. How to find the most frequent value in an array?

In [83]:
a = np.random.randint(0, 10, 50)
np.bincount(a).argmax()

0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
a = np.random.randint(0, 10, (10, 10))
sliding_window_view(a, window_shape=(3, 3))

array([[[[0, 6, 7],
         [4, 4, 1],
         [9, 0, 4]],

        [[6, 7, 6],
         [4, 1, 4],
         [0, 4, 9]],

        [[7, 6, 4],
         [1, 4, 9],
         [4, 9, 2]],

        [[6, 4, 3],
         [4, 9, 0],
         [9, 2, 1]],

        [[4, 3, 1],
         [9, 0, 9],
         [2, 1, 7]],

        [[3, 1, 0],
         [0, 9, 9],
         [1, 7, 0]],

        [[1, 0, 6],
         [9, 9, 8],
         [7, 0, 0]],

        [[0, 6, 5],
         [9, 8, 4],
         [0, 0, 8]]],


       [[[4, 4, 1],
         [9, 0, 4],
         [3, 0, 1]],

        [[4, 1, 4],
         [0, 4, 9],
         [0, 1, 3]],

        [[1, 4, 9],
         [4, 9, 2],
         [1, 3, 6]],

        [[4, 9, 0],
         [9, 2, 1],
         [3, 6, 4]],

        [[9, 0, 9],
         [2, 1, 7],
         [6, 4, 7]],

        [[0, 9, 9],
         [1, 7, 0],
         [4, 7, 8]],

        [[9, 9, 8],
         [7, 0, 0],
         [7, 8, 9]],

        [[9, 8, 4],
         [0, 0, 8],
         [8, 9, 7]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [85]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(a):
    return np.asarray(a + a.T - np.diag(a.diagonal())).view(Symetric)

a = symetric(np.random.randint(0, 10, (10, 10)))
a[1, 2] = 228
a

Symetric([[  4,   4,   7,   7,  14,   7,   6,  13,  11,   8],
          [  4,   9, 228,  10,  12,   6,   6,  12,   4,   8],
          [  7, 228,   2,   2,  11,   8,   5,  13,   8,   1],
          [  7,  10,   2,   2,   4,  14,  13,   6,   3,   9],
          [ 14,  12,  11,   4,   3,   4,  13,   3,  15,   5],
          [  7,   6,   8,  14,   4,   6,   1,   5,   4,   6],
          [  6,   6,   5,  13,  13,   1,   6,  10,   6,  18],
          [ 13,  12,  13,   6,   3,   5,  10,   1,   9,   7],
          [ 11,   4,   8,   3,  15,   4,   6,   9,   6,  10],
          [  8,   8,   1,   9,   5,   6,  18,   7,  10,   4]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [86]:
p, n = 5, 10
a = np.ones((p, n, n))
b = np.ones((p, n, 1))
o = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
o

array([[50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.],
       [50.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [87]:
a = np.ones((16, 16))
sliding_window_view(a, window_shape=(4, 4))[::4, ::4].sum(axis=(-2, -1))

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [88]:
def iterate(field):
    # Подсчет соседей
    N = (field[0:-2, 0:-2] + field[0:-2, 1:-1] + field[0:-2, 2:] +
         field[1:-1, 0:-2]                     + field[1:-1, 2:] +
         field[2:  , 0:-2] + field[2:  , 1:-1] + field[2:   ,2:])

    # Реализовываем логику для каждого числа соседей
    birth = (N == 3) & (field[1:-1, 1:-1] == 0)
    survive = ((N==2) | (N==3)) & (field[1:-1, 1:-1] == 1)
    field[...] = 0
    field[1:-1,1:-1][birth | survive] = 1
    return field

field = np.random.randint(0,2,(50,50))
for i in range(100): field = iterate(field)
field

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 89. How to get the n largest values of an array (★★★)

In [89]:
a = np.arange(100)
n = 10
print(a[np.argsort(a)[-n:]])

[90 91 92 93 94 95 96 97 98 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [90]:
# Лень думать

#### 91. How to create a record array from a regular array? (★★★)

In [91]:
a = np.array([("first", 1, 3),
              ("second", 2, 4)])
records = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
records

rec.array([(b'first', 1., 3), (b'second', 2., 4)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [92]:
Z = np.random.rand(int(100))

%timeit np.power(x,3)
%timeit x*x*x

856 ns ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.61 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [93]:
# Лень думать

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [94]:
a = np.random.randint(0, 10,(10,3))
a[~(np.all(a[:,1:] == a[:,:-1], axis=1))]

array([[3, 5, 6],
       [1, 8, 0],
       [3, 0, 9],
       [2, 4, 2],
       [3, 0, 3],
       [2, 8, 2],
       [2, 4, 7],
       [4, 2, 4],
       [1, 1, 8],
       [3, 6, 8]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [95]:
a = np.array([0, 1, 2, 4, 8, 16, 32, 64, 128], dtype=np.uint8)
np.unpackbits(a[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [96]:
a = np.random.randint(0, 10, (2, 4))
np.unique(a, axis=0)

array([[3, 9, 2, 3],
       [8, 2, 6, 7]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [97]:
a = np.random.uniform(0,1,10)
b = np.random.uniform(0,1,10)

np.einsum('i->', a)
np.einsum('i,i->i', a, b)
np.einsum('i,i', a, b)
np.einsum('i,j->ij', a, b)

array([[0.13450095, 0.48739886, 0.13240887, 0.67112761, 0.17973077,
        0.59790156, 0.41252934, 0.53086791, 0.40598591, 0.1943227 ],
       [0.06754525, 0.24476763, 0.06649463, 0.33703467, 0.09025929,
        0.30026116, 0.20716878, 0.26659742, 0.20388273, 0.09758723],
       [0.0980108 , 0.35516741, 0.09648631, 0.4890505 , 0.13096976,
        0.4356907 , 0.30061001, 0.3868433 , 0.29584182, 0.14160289],
       [0.01116691, 0.04046617, 0.01099321, 0.0557202 , 0.0149221 ,
        0.04964063, 0.03425015, 0.04407518, 0.03370688, 0.01613359],
       [0.0845171 , 0.30626949, 0.08320249, 0.42172014, 0.11293841,
        0.37570668, 0.25922332, 0.33358438, 0.25511159, 0.12210762],
       [0.12693753, 0.45999087, 0.1249631 , 0.63338797, 0.16962394,
        0.56427965, 0.3893315 , 0.50101552, 0.38315603, 0.18339531],
       [0.08523742, 0.30887978, 0.08391161, 0.42531439, 0.11390096,
        0.37890877, 0.26143264, 0.33642746, 0.25728587, 0.12314832],
       [0.00810873, 0.02938406, 0.0079826

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [98]:
# Лень думать

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
# Лень думать

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [100]:
a = np.random.randn(100)
n = 1000
idx = np.random.randint(0, a.size, (n, a.size))
means = a[idx].mean(axis=1)
confint = np.percentile(means, [3.1, 85.2])
print(confint)

[-0.08563768  0.20623796]
